# Generated by Django 5.1.2 on 2025-08-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0008_alter_healthdiary_options'),
        ('managements', '0010_alter_healthrecord_date'),
    ]

    operations = [
    ]
