# Generated by Django 5.1.2 on 2025-09-19 16:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0011_merge_20250814_1317'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Tag',
        # ),
        migrations.AlterUniqueTogether(
            name='healthdiary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.localdate, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='goal',
            field=models.CharField(choices=[('maintain', 'Duy trì'), ('lose', 'Giảm cân'), ('gain', 'Tăng cơ')], default='maintain', max_length=20),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mealplan_images/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='healthdiary',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Exerciser'), (2, 'Coach')], default=0),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='goal_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
