# Generated by Django 5.1.2 on 2025-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0011_merge_20250814_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='goal',
            field=models.CharField(choices=[('maintain', 'Duy trì'), ('lose', 'Giảm cân'), ('gain', 'Tăng cơ')], default='maintain', max_length=20),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mealplan_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Exerciser'), (2, 'Coach')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together={('sender', 'receiver', 'message', 'timestamp')},
        ),
    ]
