# Generated by Django 5.1.2 on 2025-09-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0012_delete_tag_alter_healthdiary_unique_together_and_more'),
        ('managements', '0012_delete_tag_mealplan_goal_mealplan_image_and_more'),
    ]

    operations = [
    ]
