# Generated by Django 5.1.2 on 2025-09-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0013_merge_20250919_1119'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Tag',
        # ),
        migrations.AlterField(
            model_name='healthdiary',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together={('sender', 'receiver', 'timestamp')},
        ),
    ]
